services:
  - type: web
    name: nids-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python create_model.py"
    startCommand: "python start.py"
    envVars:
      - key: SUPABASE_URL
        value: https://boyywwgvkwweupojpfwo.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_tTdmAKj540LoWuRj2KSrsA_dSlg9Usz
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: sb_secret_5N_WEzl8k33PxnyZ8RCSEg_QXekKjPs
      - key: MODEL_PATH
        value: ids_model.pkl